[[redirects]]
from = "/*"
to = "/subjects/index.html"
status = 301

[[redirects]]
from = "/*"
to = "/workshops/index.html"
status = 302

[[redirects]]
from = "/*"
to = "/testimonials/index.html"
status = 303
