[[redirects]]
  from = "/*"
  to = "/subjects/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/workshops/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/testimonials/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
